#pragma once


enum class BT_PLAYER_TYPES {
	BT_PLAYER_HUMAN, BT_PLAYER_SIZE
};

enum class BT_ENEMY_TYPES {
	BT_ENEMY_RAT, BT_ENEMY_BAT, BT_ENEMY_FLYTRAP, BT_ENEMY_SIZE
};


enum class BT_ITEM_TYPES {
	BT_ITEM_BRONZECOIN, BT_ITEM_SILVERCOIN, BT_ITEM_GOLDCOIN, BT_ITEM_SIZE
};


enum class BT_ITEM_OBSTACLE {
	BT_OBSTACLE_CRATE, BT_OBSTACLE_SPIKES, BT_OBSTACLE_UNLOCKEDDOOR, BT_OBSTACLE_LADDER, BT_ITEM_SIZE
};